---
name: pre-commit

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt repositories
        run: sudo apt update
      - name: Install pre-commit dependencies
        run: sudo apt install -y yamllint aspell
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1
